[package]
name = "egalax-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# had problems with EV_ABS
evdev-rs = "0.5"
evdev = "0.11"
input-linux = "0.5.0"
nix = "0.23"
