[monitor_designator]
Named = "HDMI-A-0"

[common]
has_moved_threshold = 30.0
ev_left_click = "BTN_LEFT"
ev_right_click = "BTN_RIGHT"

[common.calibration_points]
x1 = 300.0
y1 = 300.0
x2 = 3800.0
y2 = 3800.0

[common.right_click_wait]
secs = 1
nanos = 500000000
